### ISSUE TITLE
Valid regex seemingly fails silently?

### ISSUE THREAD

**Issue by ChasNelson1990** [fuxingloh/multi-labeler#103]
Hi there.
Just started using this action so if I'm doing something silly please let me know but I can't seem to get valid parenthesis-related regex statements working in my labeler.yml.

PR title is: "build(deps): apply minor and patch dependency updates test" - we use both "^build(deps): .*" and "^build(dev-deps): .*" commit and PR title tags and I'd like to catch both and apply a "dependencies" label.

The following labeler.yml catches that PR title and succesfully applies the label:
```
version: v1

labels:
  - label: "dependencies"
    sync: true
    matcher:
      title: "^build.*"
      commits: "^build.*"
```

However, to use parentheses I am obviously going to have to escape them. `\(` isn't valid YAML so I went for `\x28` instead and came up with the following valid regex:
```
title: "^build\x28(deps|deps-dev)\x29: .*"
```

However, the action then does nothing - officially passed but gives no useful logging output and doesn't apply the label.

Is there a debug flag for getting useful logging? And should valid regex like this work?

Any help much appreciated.
