### ISSUE TITLE
Support pinning config repo

### ISSUE THREAD

**Issue by 5ouma** [fuxingloh/multi-labeler#348]
It's nice to be able to pin the config repo by commit hash or tags.

This can be achieved by one of these solutions.

```yaml
 - uses: fuxingloh/multi-labeler@v4
   with:
     config-repo: my-org/my-repo@my-ref
```

or

```yaml
 - uses: fuxingloh/multi-labeler@v4
   with:
     config-repo: my-org/my-repo
     config-ref: my-ref
```
